name: CD - Deploy to Swarm (Docker Desktop)

on:
  workflow_run:
    workflows: ["CI/CD - Test, Build, Push Docker Image"]
    types: [completed]

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    env:
      IMAGE_NAME: caffeinatedkatze/perfume-site
      SERVICE_NAME: c270web

    steps:
      - name: Docker login
        run: echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy commit image to Swarm
        run: |
          echo "Deploying SHA: $SHA"
          docker pull $IMAGE_NAME:$SHA
          docker service update --image $IMAGE_NAME:$SHA $SERVICE_NAME
          docker service ps $SERVICE_NAME --no-trunc
        env:
          SHA: ${{ github.event.workflow_run.head_sha }}