name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .   

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  

      - name: Configure Git
        run: |
          git config --global url."https://".insteadOf git://
          git config --global url."https://".insteadOf ssh://git@
          git config --global user.email "ci@example.com"
          git config --global user.name "CI Bot"

      - name: Install dependencies
        run: npm install --force

      - name: Run tests
        env:
          NODE_ENV: test
        run: npm test
        
      - name: Build (if you have build script)
        run: npm run build --if-present
        
